# Generated by Django 4.2.6 on 2023-10-29 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('deliverytype', models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered'), ('L', 'Lost'), ('S', 'Shipped')], default='S', max_length=1)),
                ('ordertotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deliverystatus', models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered'), ('L', 'Lost'), ('S', 'Shipped')], default='P', max_length=1)),
                ('customerreturn', models.BooleanField(default=False)),
                ('customercanceled', models.BooleanField(default=False)),
                ('damage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('publish_status', models.BooleanField(default=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordergraph.orders')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordergraph.product_details')),
            ],
        ),
    ]
