# Generated by Django 4.2.7 on 2023-11-04 16:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordergraph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Street_address', models.CharField(max_length=255)),
                ('zip_code', models.PositiveIntegerField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Details',
            fields=[
                ('delivery_name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('zip_code', models.PositiveIntegerField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('tracking_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='ordergraph.orders')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordergraph.customers')),
            ],
        ),
    ]
