# Generated by Django 4.2.7 on 2023-11-04 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordergraph', '0002_customers_delivery_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='zip_code',
            field=models.IntegerField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='delivery_details',
            name='zip_code',
            field=models.IntegerField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
