# Generated by Django 4.2.7 on 2023-11-13 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordergraph', '0008_rename_name_customers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='tracking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='tracking_number', serialize=False, to='ordergraph.orders'),
        ),
    ]
