# Generated by Django 4.2.7 on 2023-11-18 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordergraph', '0009_alter_deliverydetails_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_details', to='ordergraph.customers'),
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='tracking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='delivery_details', serialize=False, to='ordergraph.orders'),
        ),
    ]
