# Generated by Django 4.2.7 on 2023-11-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordergraph', '0013_customers_dod_customers_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='dod',
            new_name='dob',
        ),
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orders',
            name='paymentstatus',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
