# Generated by Django 4.2.7 on 2023-11-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordergraph', '0014_rename_dod_customers_dob_customers_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
