# Generated by Django 4.2.7 on 2023-11-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordergraph', '0015_alter_productdetails_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='deliverytype',
            field=models.CharField(choices=[('3-Day', '3-Day'), ('Express', 'Express'), ('Standard', 'Standard')], default='Standard', max_length=50),
        ),
    ]
