# Generated by Django 4.2.7 on 2023-12-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordergraph', '0016_alter_orders_deliverytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
