# Generated by Django 4.2.7 on 2023-11-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordergraph', '0004_rename_tracking_id_delivery_details_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_details',
            name='city',
        ),
        migrations.RemoveField(
            model_name='delivery_details',
            name='delivery_name',
        ),
        migrations.RemoveField(
            model_name='delivery_details',
            name='state',
        ),
        migrations.RemoveField(
            model_name='delivery_details',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='delivery_details',
            name='zip_code',
        ),
    ]
