# Generated by Django 4.2.7 on 2023-11-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordergraph', '0005_remove_delivery_details_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_details',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ordergraph.customers'),
        ),
        migrations.AlterField(
            model_name='delivery_details',
            name='tracking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='ordergraph.orders'),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ordergraph.orders'),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='product_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ordergraph.product_details'),
        ),
    ]
