# Generated by Django 4.2.7 on 2023-11-04 22:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ordergraph', '0001_initial'), ('ordergraph', '0002_customers_delivery_details'), ('ordergraph', '0003_alter_customers_zip_code_and_more'), ('ordergraph', '0004_rename_tracking_id_delivery_details_tracking')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('deliverytype', models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered'), ('L', 'Lost'), ('S', 'Shipped')], default='S', max_length=1)),
                ('ordertotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deliverystatus', models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered'), ('L', 'Lost'), ('S', 'Shipped')], default='P', max_length=1)),
                ('customerreturn', models.BooleanField(default=False)),
                ('customercanceled', models.BooleanField(default=False)),
                ('damage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('publish_status', models.BooleanField(default=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordergraph.orders')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordergraph.product_details')),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Street_address', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Details',
            fields=[
                ('delivery_name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('tracking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='ordergraph.orders')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordergraph.customers')),
            ],
        ),
    ]
