# Generated by Django 4.2.7 on 2023-11-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordergraph', '0006_alter_delivery_details_customer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery_Details',
            new_name='DeliveryDetails',
        ),
        migrations.RenameModel(
            old_name='Order_Product',
            new_name='OrderProduct',
        ),
        migrations.RenameModel(
            old_name='Product_Details',
            new_name='ProductDetails',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_details',
            new_name='productdetails',
        ),
    ]
